CREATE DATABASE picture_this;
CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    username VARCHAR(50) NOT NULL,
    hash VARCHAR(100) NOT NULL
);
CREATE TABLE rooms (
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(50) NOT NULL,
    created_at VARCHAR(50) NOT NULL,
    created_by VARCHAR(50) NOT NULL
);
CREATE TABLE room_members (
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    room_name VARCHAR(50) NOT NULL,
    is_room_admin BOOLEAN 
    added_at VARCHAR(50) NOT NULL,
    added_by VARCHAR(50) NOT NULL
);